## Answer [/problems/{id}/answers]
+ Parameters
    + id (string) - The ID of the Problem

### Answer a Problem [POST]
User can answer a Problem. Answers are not persistent. 
Only if a question is answered correctly for the first time, the Problem.answered is switched to `true`

+ Request (application/json)
    + Headers
        Authorization: Basic ABC123
    + Attributes(Answer)

+ Response 200 (application/json)
    + Attributes(Answer)
        + correct: (boolean)
