## Problem [/problem/{id}]

### Read Existing Problem [GET]

+ Response 200 (application/json)

### Create Problem [POST]

+ Request (application/json)
    + Attributes(Problem.Create)

+ Response 201 (application/json)

### Update Problem [PUT]

+ Response 200 (application/json)

