## Problem [/problem/{id}]
A Problem contains information about the type of problem, its query and whether it has been correctly answered.

+ Parameters
    + id (string) - The ID of the Problem

### Read Existing Problem [GET]

+ Request
    + Headers
        Authorization: Basic ABC123

+ Response 200 (application/json)
    + Attributes (Problem.Base)

### Create Problem [POST]
User can update a Problem.

+ Request (application/json)
    + Headers
        Authorization: Basic ABC123
    + Attributes(Problem.Create)

+ Response 201 (application/json)
    + Attributes (Problem.Base)

### Update Problem [PUT]
User can update a Problem. Only user that originally created the Problem is allowed to update it.

+ Request
    + Headers
        Authorization: Basic ABC123

+ Response 200 (application/json)
    + Attributes (Problem.Base)

+ Response 403

### Delete Problem [DELETE]
User can delete a Problem. Only user that originally created the Problem is allowed to delete it.

+ Request
    + Headers
        Authorization: Basic ABC123

+ Response 204

+ Response 403
