
## Problem.Base (object)
+ id: 1 (number) - An unique identifier of the Problem
+ type: `riddle` (string, required)
+ query: `If two is a company and three is a crowd. What is four and five?` (string, required) - Body of the problem
+ createdBy: `Alice` (string) - Username of the user who created this problem


## Problem.Create (object)
+ type: `riddle` (string, required)
+ query: `If two is a company and three is a crowd. What is four and five?` (string, required) -  Body of the problem
