
## Problem (object)
+ id: 1 (number) - An unique identifier of the Problem
+ answered (boolean) - Does the question have any answers?


## Problem.Create (object)
+ type: `riddle` (string, required)

    Body of the problem

+ query: `If two is a company and three is a crowd. What is four and five?` (string, required)
