FORMAT: 1A

# The Problematic API

This API is all about Problems.

## GitHub repository

https://github.com/tond4/the-problematic-api


<!-- include(collections/index.apib) -->
<!-- include(schemas/index.apib) -->
